# Generated by Django 3.1.4 on 2021-01-04 17:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='partNumber',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
