# Generated by Django 3.1.4 on 2021-01-05 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_category_item_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_details',
            name='item_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.category'),
        ),
    ]
